train_file: './dataset/twitter/train.txt'
val_file: './dataset/twitter/dev.txt'
test_file: './dataset/twitter/test.txt'

image_root: './dataset/twitter'
# hidden_size: 768
image_res: 224 
#image_res: [224, 224]  # 或者 image_res: (224, 224)
# image_res: 384
batch_size_train: 32
batch_size_test: 64
max_text_len: 512
# alpha: 0.4
max_image_len: -1
distill: True
warm_up: False
vit: "vit_base_patch32_384"
bert_config: 'configs/config_bert.json'
drop_rate: 0.1
optimizer_lr: 1e-3
schedular_lr: 1e-3
warmup_lr: 9e-5
optimizer: {opt: adamW, lr: 1e-3, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-3, epochs: 30, min_lr: 1e-7, decay_rate: 1, warmup_lr: 9e-5, warmup_epochs: 1, cooldown_epochs: 0}

# new
output_dir: './output/'
load_path: ''
text_encoder: 'bert-base-uncased'
evaluate: false
device: 'cuda:0'
seed: 42
world_size: 1
dist_url: 'env://'
distributed: false
prompt_length: 16
batch_size: 64
type: 'train'
class_num: 24
test_only: false
hidden_size: 768
mmdlayer: 0
ca_loss: false
lr: 1e-5
train_dataset: 'train.txt'
test_dataset: 'test.txt'
dev_dataset: 'dev.txt'
alpha: 0.7
beta: 0.7
memory_length: 20
shreshold: 0.5

# PMF模型参数
n_encoder: 4
n_fusion: 4
n_trans: 4
mlp_hidden_sz: 1
n_fusion_layers: 10
file_path: 'only_mm'
args_file: ''

# 其他参数
use_adapter: false
use_cls: true
use_gate: false
use_layer_gate: true
use_ca_loss: true
all_cat: true
use_prompt: true
setting: 'multimodal'
model: 'baseline'




